/* zip_cp437.h -- the CP437 high-half name table (ADR 29 D6).
 * Generated by tools/gen_zip_cp437.py from the python cp437
 * codec; nothing vendored, nothing hand-edited (the ADR 28
 * entity-table discipline). Regenerate:
 *
 *     python3 tools/gen_zip_cp437.py
 *
 * Entry i holds the UTF-8 encoding of CP437 byte 0x80+i, so zip
 * names without the language-encoding flag (bit 11) decode
 * exactly as python's zipfile decodes them (0x00-0x7F map to
 * themselves and never consult this table).
 */
#ifndef MINO_ZIP_CP437_H
#define MINO_ZIP_CP437_H

static const char *const k_zip_cp437_high[128] = {
    "\xc3\x87", /* 0x80 U+00C7 Ç */
    "\xc3\xbc", /* 0x81 U+00FC ü */
    "\xc3\xa9", /* 0x82 U+00E9 é */
    "\xc3\xa2", /* 0x83 U+00E2 â */
    "\xc3\xa4", /* 0x84 U+00E4 ä */
    "\xc3\xa0", /* 0x85 U+00E0 à */
    "\xc3\xa5", /* 0x86 U+00E5 å */
    "\xc3\xa7", /* 0x87 U+00E7 ç */
    "\xc3\xaa", /* 0x88 U+00EA ê */
    "\xc3\xab", /* 0x89 U+00EB ë */
    "\xc3\xa8", /* 0x8a U+00E8 è */
    "\xc3\xaf", /* 0x8b U+00EF ï */
    "\xc3\xae", /* 0x8c U+00EE î */
    "\xc3\xac", /* 0x8d U+00EC ì */
    "\xc3\x84", /* 0x8e U+00C4 Ä */
    "\xc3\x85", /* 0x8f U+00C5 Å */
    "\xc3\x89", /* 0x90 U+00C9 É */
    "\xc3\xa6", /* 0x91 U+00E6 æ */
    "\xc3\x86", /* 0x92 U+00C6 Æ */
    "\xc3\xb4", /* 0x93 U+00F4 ô */
    "\xc3\xb6", /* 0x94 U+00F6 ö */
    "\xc3\xb2", /* 0x95 U+00F2 ò */
    "\xc3\xbb", /* 0x96 U+00FB û */
    "\xc3\xb9", /* 0x97 U+00F9 ù */
    "\xc3\xbf", /* 0x98 U+00FF ÿ */
    "\xc3\x96", /* 0x99 U+00D6 Ö */
    "\xc3\x9c", /* 0x9a U+00DC Ü */
    "\xc2\xa2", /* 0x9b U+00A2 ¢ */
    "\xc2\xa3", /* 0x9c U+00A3 £ */
    "\xc2\xa5", /* 0x9d U+00A5 ¥ */
    "\xe2\x82\xa7", /* 0x9e U+20A7 ₧ */
    "\xc6\x92", /* 0x9f U+0192 ƒ */
    "\xc3\xa1", /* 0xa0 U+00E1 á */
    "\xc3\xad", /* 0xa1 U+00ED í */
    "\xc3\xb3", /* 0xa2 U+00F3 ó */
    "\xc3\xba", /* 0xa3 U+00FA ú */
    "\xc3\xb1", /* 0xa4 U+00F1 ñ */
    "\xc3\x91", /* 0xa5 U+00D1 Ñ */
    "\xc2\xaa", /* 0xa6 U+00AA ª */
    "\xc2\xba", /* 0xa7 U+00BA º */
    "\xc2\xbf", /* 0xa8 U+00BF ¿ */
    "\xe2\x8c\x90", /* 0xa9 U+2310 ⌐ */
    "\xc2\xac", /* 0xaa U+00AC ¬ */
    "\xc2\xbd", /* 0xab U+00BD ½ */
    "\xc2\xbc", /* 0xac U+00BC ¼ */
    "\xc2\xa1", /* 0xad U+00A1 ¡ */
    "\xc2\xab", /* 0xae U+00AB « */
    "\xc2\xbb", /* 0xaf U+00BB » */
    "\xe2\x96\x91", /* 0xb0 U+2591 ░ */
    "\xe2\x96\x92", /* 0xb1 U+2592 ▒ */
    "\xe2\x96\x93", /* 0xb2 U+2593 ▓ */
    "\xe2\x94\x82", /* 0xb3 U+2502 │ */
    "\xe2\x94\xa4", /* 0xb4 U+2524 ┤ */
    "\xe2\x95\xa1", /* 0xb5 U+2561 ╡ */
    "\xe2\x95\xa2", /* 0xb6 U+2562 ╢ */
    "\xe2\x95\x96", /* 0xb7 U+2556 ╖ */
    "\xe2\x95\x95", /* 0xb8 U+2555 ╕ */
    "\xe2\x95\xa3", /* 0xb9 U+2563 ╣ */
    "\xe2\x95\x91", /* 0xba U+2551 ║ */
    "\xe2\x95\x97", /* 0xbb U+2557 ╗ */
    "\xe2\x95\x9d", /* 0xbc U+255D ╝ */
    "\xe2\x95\x9c", /* 0xbd U+255C ╜ */
    "\xe2\x95\x9b", /* 0xbe U+255B ╛ */
    "\xe2\x94\x90", /* 0xbf U+2510 ┐ */
    "\xe2\x94\x94", /* 0xc0 U+2514 └ */
    "\xe2\x94\xb4", /* 0xc1 U+2534 ┴ */
    "\xe2\x94\xac", /* 0xc2 U+252C ┬ */
    "\xe2\x94\x9c", /* 0xc3 U+251C ├ */
    "\xe2\x94\x80", /* 0xc4 U+2500 ─ */
    "\xe2\x94\xbc", /* 0xc5 U+253C ┼ */
    "\xe2\x95\x9e", /* 0xc6 U+255E ╞ */
    "\xe2\x95\x9f", /* 0xc7 U+255F ╟ */
    "\xe2\x95\x9a", /* 0xc8 U+255A ╚ */
    "\xe2\x95\x94", /* 0xc9 U+2554 ╔ */
    "\xe2\x95\xa9", /* 0xca U+2569 ╩ */
    "\xe2\x95\xa6", /* 0xcb U+2566 ╦ */
    "\xe2\x95\xa0", /* 0xcc U+2560 ╠ */
    "\xe2\x95\x90", /* 0xcd U+2550 ═ */
    "\xe2\x95\xac", /* 0xce U+256C ╬ */
    "\xe2\x95\xa7", /* 0xcf U+2567 ╧ */
    "\xe2\x95\xa8", /* 0xd0 U+2568 ╨ */
    "\xe2\x95\xa4", /* 0xd1 U+2564 ╤ */
    "\xe2\x95\xa5", /* 0xd2 U+2565 ╥ */
    "\xe2\x95\x99", /* 0xd3 U+2559 ╙ */
    "\xe2\x95\x98", /* 0xd4 U+2558 ╘ */
    "\xe2\x95\x92", /* 0xd5 U+2552 ╒ */
    "\xe2\x95\x93", /* 0xd6 U+2553 ╓ */
    "\xe2\x95\xab", /* 0xd7 U+256B ╫ */
    "\xe2\x95\xaa", /* 0xd8 U+256A ╪ */
    "\xe2\x94\x98", /* 0xd9 U+2518 ┘ */
    "\xe2\x94\x8c", /* 0xda U+250C ┌ */
    "\xe2\x96\x88", /* 0xdb U+2588 █ */
    "\xe2\x96\x84", /* 0xdc U+2584 ▄ */
    "\xe2\x96\x8c", /* 0xdd U+258C ▌ */
    "\xe2\x96\x90", /* 0xde U+2590 ▐ */
    "\xe2\x96\x80", /* 0xdf U+2580 ▀ */
    "\xce\xb1", /* 0xe0 U+03B1 α */
    "\xc3\x9f", /* 0xe1 U+00DF ß */
    "\xce\x93", /* 0xe2 U+0393 Γ */
    "\xcf\x80", /* 0xe3 U+03C0 π */
    "\xce\xa3", /* 0xe4 U+03A3 Σ */
    "\xcf\x83", /* 0xe5 U+03C3 σ */
    "\xc2\xb5", /* 0xe6 U+00B5 µ */
    "\xcf\x84", /* 0xe7 U+03C4 τ */
    "\xce\xa6", /* 0xe8 U+03A6 Φ */
    "\xce\x98", /* 0xe9 U+0398 Θ */
    "\xce\xa9", /* 0xea U+03A9 Ω */
    "\xce\xb4", /* 0xeb U+03B4 δ */
    "\xe2\x88\x9e", /* 0xec U+221E ∞ */
    "\xcf\x86", /* 0xed U+03C6 φ */
    "\xce\xb5", /* 0xee U+03B5 ε */
    "\xe2\x88\xa9", /* 0xef U+2229 ∩ */
    "\xe2\x89\xa1", /* 0xf0 U+2261 ≡ */
    "\xc2\xb1", /* 0xf1 U+00B1 ± */
    "\xe2\x89\xa5", /* 0xf2 U+2265 ≥ */
    "\xe2\x89\xa4", /* 0xf3 U+2264 ≤ */
    "\xe2\x8c\xa0", /* 0xf4 U+2320 ⌠ */
    "\xe2\x8c\xa1", /* 0xf5 U+2321 ⌡ */
    "\xc3\xb7", /* 0xf6 U+00F7 ÷ */
    "\xe2\x89\x88", /* 0xf7 U+2248 ≈ */
    "\xc2\xb0", /* 0xf8 U+00B0 ° */
    "\xe2\x88\x99", /* 0xf9 U+2219 ∙ */
    "\xc2\xb7", /* 0xfa U+00B7 · */
    "\xe2\x88\x9a", /* 0xfb U+221A √ */
    "\xe2\x81\xbf", /* 0xfc U+207F ⁿ */
    "\xc2\xb2", /* 0xfd U+00B2 ² */
    "\xe2\x96\xa0", /* 0xfe U+25A0 ■ */
    "\xc2\xa0", /* 0xff U+00A0   */
};

#endif /* MINO_ZIP_CP437_H */
