/*
 * stencil_extract/core.c -- format-agnostic plumbing implementation.
 * read_file / blob_free / sym_table_intern / write_stencil_header.
 */

#include "core.h"

#include <stdlib.h>
#include <string.h>

int read_file(const char *path, mblob_t *out)
{
    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        fprintf(stderr, "stencil_extract: cannot open '%s'\n", path);
        return -1;
    }
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return -1; }
    long sz = ftell(f);
    if (sz < 0) { fclose(f); return -1; }
    if (fseek(f, 0, SEEK_SET) != 0) { fclose(f); return -1; }
    uint8_t *buf = (uint8_t *)malloc((size_t)sz);
    if (buf == NULL) { fclose(f); return -1; }
    size_t n = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    if (n != (size_t)sz) { free(buf); return -1; }
    out->data = buf;
    out->len  = (size_t)sz;
    return 0;
}

void blob_free(mblob_t *b) { free(b->data); b->data = NULL; b->len = 0; }

int sym_table_intern(const char *name,
                     const char **table, int *count, int cap)
{
    for (int i = 0; i < *count; i++) {
        if (strcmp(table[i], name) == 0) return i;
    }
    if (*count >= cap) return -1;
    table[*count] = name;
    return (*count)++;
}

int write_stencil_header(const char *symbol,
                         const uint8_t *body, uint64_t size,
                         const stencil_reloc_t *relocs, int nrelocs,
                         const char *const *syms, int nsyms,
                         const char *out_path, int append)
{
    FILE *out = (out_path != NULL && strcmp(out_path, "-") != 0)
        ? fopen(out_path, append ? "a" : "w") : stdout;
    if (out == NULL) {
        fprintf(stderr, "stencil_extract: cannot open '%s' for write\n",
                out_path);
        return -1;
    }
    if (!append) {
        fprintf(out, "/* Generated by tools/stencil_extract. Do not edit. */\n\n");
    } else {
        fprintf(out, "\n");
    }
    fprintf(out, "static const unsigned char %s_bytes[%" PRIu64 "] = {\n",
            symbol, size);
    for (uint64_t i = 0; i < size; i++) {
        if ((i & 15) == 0) fprintf(out, "    ");
        fprintf(out, "0x%02x", body[i]);
        if (i + 1 < size) fprintf(out, ",");
        if ((i & 15) == 15) fprintf(out, "\n");
        else                fprintf(out, " ");
    }
    if ((size & 15) != 0) fprintf(out, "\n");
    fprintf(out, "};\n");
    fprintf(out, "static const unsigned long %s_size = %" PRIu64 ";\n",
            symbol, size);
    /* Symbol table for this stencil: each reloc references a symbol by
     * its index in this table. */
    fprintf(out, "static const char *const %s_symbols[%d] = {\n",
            symbol, nsyms == 0 ? 1 : nsyms);
    if (nsyms == 0) {
        fprintf(out, "    0\n");
    } else {
        for (int i = 0; i < nsyms; i++) {
            fprintf(out, "    \"%s\"%s\n", syms[i], i + 1 < nsyms ? "," : "");
        }
    }
    fprintf(out, "};\n");
    fprintf(out, "static const unsigned long %s_nsymbols = %d;\n",
            symbol, nsyms);
    /* Reloc table emitted as quadruples (offset, kind, sym_index,
     * addend). Empty when the stencil takes no immediates. */
    fprintf(out, "static const unsigned int %s_relocs[%d][4] = {\n",
            symbol, nrelocs == 0 ? 1 : nrelocs);
    if (nrelocs == 0) {
        fprintf(out, "    {0, 0, 0, 0}\n");
    } else {
        for (int i = 0; i < nrelocs; i++) {
            fprintf(out, "    {%u, %u, %u, %d}%s\n",
                    relocs[i].offset, relocs[i].kind,
                    relocs[i].sym_index, relocs[i].addend,
                    i + 1 < nrelocs ? "," : "");
        }
    }
    fprintf(out, "};\n");
    fprintf(out, "static const unsigned long %s_nrelocs = %d;\n",
            symbol, nrelocs);
    if (out != stdout) fclose(out);
    return 0;
}
