;; Test runner: loads all test files and runs them.
;; Usage: ./mino tests/run.clj
;;
;; suite-mode is set to true around the require chain so each test
;; file's bottom (run-tests-and-exit) call is a no-op. The final
;; (run-tests-and-exit) runs the accumulated registry once,
;; end-to-end, and exits with 0 on success or 1 on any failure.

(require "tests/test")

(reset! clojure.test/suite-mode true)

(require "tests/compat_test")
(require "tests/arithmetic_test")
(require "tests/binding_test")
(require "tests/control_test")
(require "tests/function_test")
(require "tests/arity_strict_test")
(require "tests/collection_test")
(require "tests/string_test")
(require "tests/sequence_test")
(require "tests/lazy_test")
(require "tests/lazy_seq_ns_scope_test")
(require "tests/macro_test")
(require "tests/error_test")
(require "tests/atom_test")
(require "tests/stm_test")
(require "tests/predicate_test")
(require "tests/io_test")
(require "tests/reflection_test")
(require "tests/repl_test")
(require "tests/gc_test")
(require "tests/regression_bc_clause_params_gc")
(require "tests/math_test")
(require "tests/hash_compare_test")
(require "tests/regex_test")
(require "tests/tco_test")
(require "tests/core_extra_test")
(require "tests/destructuring_test")
(require "tests/reader_macros_test")
(require "tests/phase3_test")
(require "tests/finally_test")
(require "tests/protocol_test")
(require "tests/core_protocols_test")
(require "tests/iteration_test")
(require "tests/metadata_test")
(require "tests/transducer_test")
(require "tests/dialect_test")
(require "tests/clj_sequences_test")
(require "tests/clj_predicates_test")
(require "tests/clj_control_test")
(require "tests/clj_math_test")
(require "tests/clj_higher_order_test")
(require "tests/clj_transducer_test")
(require "tests/clj_metadata_test")
(require "tests/empty_list_test")
(require "tests/error_path_test")
(require "tests/bc_try_catch_test")
(require "tests/bc_error_quality_test")
(require "tests/jit_parity_test")
(require "tests/jit_invalidation_test")
(require "tests/bc_binding_test")
(require "tests/bc_destructure_test")
(require "tests/bc_closure_test")
(require "tests/reduce_perf_test")
(require "tests/bc_let_fold_test")
(require "tests/bc_bitwise_test")
(require "tests/ifn_test")
(require "tests/stack_test")
(require "tests/sorted_test")
(require "tests/transient_test")
(require "tests/print_method_test")
(require "tests/print_dynvars_test")
(require "tests/conformance_test")
(require "tests/var_quote_test")
(require "tests/reader_cond_test")
(require "tests/ns_test")
(require "tests/require_extended_test")
(require "tests/var_test")
(require "tests/ns_resolution_test")
(require "tests/are_test")
(require "tests/literal_test")
(require "tests/char_test")
(require "tests/numeric_tower_test")
(require "tests/numeric_edges_test")
(require "tests/collections_semantics_test")
(require "tests/stateful_test")
(require "tests/hierarchy_test")
(require "tests/multimethod_test")
(require "tests/clojure_string_test")
(require "tests/tasks_test")
(require "tests/records_test")
(require "tests/instant_template_test")
(require "tests/data_test")
(require "tests/data_readers_test")
(require "tests/reader_conditional_test")
(require "tests/queue_test")
(require "tests/spec_test")
(require "tests/reducers_test")
(require "tests/capability_metadata_test")
(require "tests/async_smoke_test")
(require "tests/parallel_calls_test")
(require "tests/parallel_fold_test")
(require "tests/test_check_shrinking_test")
(require "tests/fs_test")
(require "tests/proc_test")
(require "tests/deps_test")

(reset! clojure.test/suite-mode false)

(run-tests-and-exit)
