(require "tests/test")
(require '[clojure.string :as str])
(require '[clojure.edn :as edn])
(require '[clojure.xml :as xml])
(require '[clojure.test.junit :as junit])

;; Strict XML reader tests (html-xml campaign p5, ADR 28).
;;
;; Three layers, one file:
;;
;; 1. The golden corpus: tests/fixtures/xml/golden.edn is the
;;    python3 xml.etree well-formed oracle dump (generated by
;;    tools/gen_xml_oracle.py). Every vector parses to the JVM
;;    clojure.xml node shape; the golden carries string tags and
;;    attribute names, keywordized here at the comparison boundary
;;    (the p1 golden decision). The corpus's divergence ledger
;;    (the file's header) names the classes the corpus excludes;
;;    those are the hand vectors below.
;;
;; 2. Strictness vectors (hand-written, D11): the design's XML
;;    delta set against the shared tokenizer - case-sensitive
;;    names, the five predefined entities plus numeric references
;;    only, DOCTYPE dropped but internal-subset ENTITY rejected
;;    (D3: XXE structurally impossible), CDATA capture, PIs
;;    dropped, mandatory attribute quoting, single root, prolog
;;    checks, attribute whitespace normalization, the 256 nesting
;;    cap. The qname vectors pin the documented divergences from
;;    the python oracle (ledger line 2): literal prefix:local
;;    keywords, xmlns attributes kept, undeclared prefixes
;;    accepted (the JVM SAX behavior, not etree's).
;;
;; 3. Error shapes: malformed vectors with :code keywords and
;;    byte-exact :location line/col, pinned against the prim's
;;    descriptor ([:xml/error code line col text]); the facade
;;    owns the positioned ex-info conversion (p5t3 vectors).
;;
;; Positions are the design's contract: 1-based line and column
;;    over bytes, at the token start ('<' of the construct, '&'
;;    of the reference, the offending byte, or EOF).

;;; ---- node builders ----

(defn- xml-el
  ([tag] {:tag tag :attrs {} :content []})
  ([tag content] {:tag tag :attrs {} :content content})
  ([tag attrs content] {:tag tag :attrs attrs :content content}))

(defn- xml-err
  "Runs (xml-parse s nil) and returns the error descriptor vector,
  the tree, or the thrown value."
  [s]
  (try (xml-parse s nil) (catch Throwable e e)))

;;; ---- golden corpus ----

(def ^:private xml-golden-all
  (edn/read-string (slurp "tests/fixtures/xml/golden.edn")))

(defn- xml-golden-kw-node
  "Keywordize a golden :tree node per the JVM clojure.xml shape
  (element tags and attr keys become keywords; text strings and
  attr values pass through)."
  [node]
  (if (string? node)
    node
    {:tag (keyword (:tag node))
     :attrs (reduce (fn [m [k v]] (assoc m (keyword k) v))
                    {} (:attrs node))
     :content (mapv xml-golden-kw-node (:content node))}))

(deftest xml-golden-corpus-matches-the-reader
  (let [res (reduce
              (fn [acc v]
                (if (= (xml-golden-kw-node (:tree v))
                       (xml-parse (:input v) nil))
                  (assoc acc :ok (inc (:ok acc)))
                  (-> acc
                      (assoc :fail (inc (:fail acc)))
                      (assoc :first-fail (:id v)))))
              {:ok 0 :fail 0 :first-fail nil}
              xml-golden-all)]
    (is (zero? (:fail res))
        (str "golden mismatches: " (:fail res) " first id "
             (:first-fail res)))
    (is (> (:ok res) 30)
        (str "corpus coverage collapsed: only " (:ok res) " compared"))))

;;; ---- strictness vectors (hand-pinned, spec-cited) ----

;; XML delta: case-sensitive names; no lowercasing (HTML rule 11 is
;; HTML-mode only). Pinned by goldens too; these make the rule
;; explicit against the shared tokenizer.
(deftest xml-strict-case-sensitive-names
  (is (= (xml-el :Mixed ["CASE"])
         (xml-parse "<Mixed>CASE</Mixed>" nil)))
  (is (= (xml-el :r [(xml-el :Case ["c"]) (xml-el :case ["d"])])
         (xml-parse "<r><Case>c</Case><case>d</case></r>" nil))))

;; D3: five predefined entities plus numeric character references
;; only, in text and attribute values.
(deftest xml-strict-entity-rules
  (is (= (xml-el :a ["\"'<>&"])
         (xml-parse "<a>&quot;&apos;&lt;&gt;&amp;</a>" nil)))
  (is (= (xml-el :a {:t "&<>\"'"} [])
         (xml-parse "<a t=\"&amp;&lt;&gt;&quot;&apos;\"/>" nil)))
  (is (= (xml-el :a ["&#38;&#38;"])
         (xml-parse "<a>&#38;#38;&#x26;#38;</a>" nil)))
  ;; ANY other named entity is :undefined-entity (D3)
  (is (= [:xml/error "undefined-entity" 1 4]
         (take 4 (xml-err "<a>&nbsp;</a>"))))
  (is (= [:xml/error "undefined-entity" 1 6]
         (take 4 (xml-err "<a>x &amp y</a>"))))
  ;; missing semicolon is not a reference
  (is (= [:xml/error "undefined-entity" 1 4]
         (take 4 (xml-err "<a>&amp</a>"))))
  ;; numeric range policing: 0, surrogates, > 0x10FFFF reject
  (is (= [:xml/error "undefined-entity" 1 4]
         (take 4 (xml-err "<a>&#0;</a>"))))
  (is (= [:xml/error "undefined-entity" 1 4]
         (take 4 (xml-err "<a>&#xD800;</a>"))))
  (is (= [:xml/error "undefined-entity" 1 4]
         (take 4 (xml-err "<a>&#x110000;</a>"))))
  (is (= [:xml/error "undefined-entity" 1 4]
         (take 4 (xml-err "<a>&#x;</a>")))))

;; D3: DOCTYPE accepted and dropped; an internal-subset ENTITY
;; declaration throws :unsupported-doctype (nothing is ever honored
;; or fetched: XXE is impossible by construction).
(deftest xml-strict-doctype-rules
  (is (= (xml-el :r [])
         (xml-parse "<!DOCTYPE r><r/>" nil)))
  (is (= (xml-el :r ["t"])
         (xml-parse "<!DOCTYPE r SYSTEM \"x.dtd\"><r>t</r>" nil)))
  (is (= (xml-el :r ["t"])
         (xml-parse
           "<!DOCTYPE r [<!-- c --><!ELEMENT r (#PCDATA)>]><r>t</r>" nil)))
  (is (= [:xml/error "unsupported-doctype" 1 14]
         (take 4 (xml-err "<!DOCTYPE a [<!ENTITY e \"x\">]><a/>"))))
  (is (= [:xml/error "unsupported-doctype" 1 14]
         (take 4 (xml-err
                   "<!DOCTYPE a [<!ENTITY % p \"x\">]><a/>"))))
  ;; a second DOCTYPE and a post-root DOCTYPE are prolog errors
  (is (= [:xml/error "invalid-prolog" 1 13]
         (take 4 (xml-err "<!DOCTYPE a><!DOCTYPE b><a/>"))))
  (is (= [:xml/error "invalid-prolog" 1 5]
         (take 4 (xml-err "<a/><!DOCTYPE b>")))))

;; XML delta: CDATA captured as text (merging with adjacent runs,
;; markup and ampersands literal); PIs dropped everywhere.
(deftest xml-strict-cdata-and-pis
  (is (= (xml-el :a ["x<b>&amp;"])
         (xml-parse "<a>x<![CDATA[<b>&amp;]]></a>" nil)))
  (is (= (xml-el :a ["raw & <text>"])
         (xml-parse "<a><![CDATA[raw & <text>]]></a>" nil)))
  (is (= (xml-el :a [])
         (xml-parse "<a><![CDATA[]]></a>" nil)))
  (is (= (xml-el :a ["onetwothree"])
         (xml-parse "<a>one<!--c-->two<?pi x?>three</a>" nil)))
  (is (= (xml-el :r ["xy"])
         (xml-parse "<?pi data?><r>x<?pi2?>y</r>" nil))))

;; XML delta: attribute values must be quoted (XML 1.0 3.3); no
;; valueless attributes; whitespace must separate attributes.
(deftest xml-strict-mandatory-attribute-quoting
  (is (= [:xml/error "unexpected-token" 1 6]
         (take 4 (xml-err "<a b=c/>"))))
  (is (= [:xml/error "unexpected-token" 1 6]
         (take 4 (xml-err "<a b=c=\"d\"/>"))))
  (is (= [:xml/error "unexpected-token" 1 5]
         (take 4 (xml-err "<a b>"))))
  (is (= [:xml/error "unexpected-token" 1 9]
         (take 4 (xml-err "<a b=\"1\"c=\"2\"/>"))))
  ;; a literal < inside a quoted value is not well-formed
  (is (= [:xml/error "unexpected-token" 1 7]
         (take 4 (xml-err "<a b=\"<\"/>")))))

;; XML delta: exactly one root element; character data outside the
;; root is an error; whitespace outside is allowed.
(deftest xml-strict-single-root
  (is (= [:xml/error "multiple-roots" 1 5]
         (take 4 (xml-err "<a/><b/>"))))
  (is (= [:xml/error "multiple-roots" 2 1]
         (take 4 (xml-err "<a/>\n<b/>"))))
  (is (= [:xml/error "content-before-root" 1 1]
         (take 4 (xml-err "x<a/>"))))
  (is (= [:xml/error "content-before-root" 1 5]
         (take 4 (xml-err "<a/>x"))))
  (is (= [:xml/error "content-before-root" 1 6]
         (take 4 (xml-err "<a/> <![CDATA[x]]>"))))
  ;; whitespace around the root is fine
  (is (= (xml-el :r ["t"])
         (xml-parse "\n  <r>t</r>\n\n" nil))))

;; XML delta: prolog checks. The XML declaration is only valid as
;; the first bytes, exactly lowercase; a PI target matching xml
;; case-insensitively is reserved anywhere.
(deftest xml-strict-prolog
  (is (= (xml-el :r [])
         (xml-parse "<?xml version=\"1.0\"?><r/>" nil)))
  (is (= (xml-el :r [])
         (xml-parse
           "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><r/>"
           nil)))
  (is (= [:xml/error "invalid-prolog" 1 1]
         (take 4 (xml-err "<?XML version=\"1.0\"?><a/>"))))
  (is (= [:xml/error "invalid-prolog" 1 9]
         (take 4 (xml-err "<!--c--><?xml version=\"1.0\"?><a/>"))))
  (is (= [:xml/error "invalid-prolog" 1 22]
         (take 4 (xml-err
                   "<?xml version=\"1.0\"?><?xml version=\"1.0\"?><a/>"))))
  (is (= [:xml/error "invalid-prolog" 1 4]
         (take 4 (xml-err "<a><?xml version=\"1.0\"?></a>"))))
  ;; a declaration without version is malformed
  (is (= [:xml/error "invalid-prolog" 1 1]
         (take 4 (xml-err "<?xml encoding=\"UTF-8\"?><a/>")))))

;; XML 1.0 3.3.3 attribute-value normalization: literal tab, CR,
;; and LF become one space each (CR LF together one space);
;; character references pass through verbatim. HTML mode does not
;; normalize (pinned on the html side).
(deftest xml-strict-attribute-whitespace-normalization
  (is (= (xml-el :a {:t "x y" :u "x y" :v "x y"} [])
         (xml-parse "<a t=\"x\ty\" u=\"x\ny\" v=\"x\r\ny\"/>" nil)))
  (is (= (xml-el :a {:t "\tx\ny\rz"} [])
         (xml-parse "<a t=\"&#9;x&#10;y&#13;z\"/>" nil))))

;; qname divergences from the python oracle (golden ledger line 2):
;; literal prefix:local keywords, xmlns attributes kept as ordinary
;; attributes, undeclared prefixes accepted (JVM SAX behavior).
(deftest xml-strict-qnames
  (is (= (xml-el :rss
                 {:xmlns/dc "urn:x" :version "2.0"}
                 [(xml-el :channel [(xml-el :dc/creator ["x"])])])
         (xml-parse
           "<rss xmlns:dc=\"urn:x\" version=\"2.0\"><channel><dc:creator>x</dc:creator></channel></rss>"
           nil)))
  (is (= (xml-el :a {:xml/lang "en"} [])
         (xml-parse "<a xml:lang=\"en\"/>" nil)))
  (is (= (xml-el :ns/a {:ns/b "1"} [])
         (xml-parse "<ns:a ns:b=\"1\"/>" nil))))

;;; ---- error shapes ----

;; Strictness: mismatched and stray end tags error (no pop-until,
;; no stray-drop: those are HTML-tier recoveries).
(deftest xml-error-mismatched-end-tags
  (is (= [:xml/error "mismatched-end-tag" 1 4]
         (take 4 (xml-err "<a></b>"))))
  (is (= [:xml/error "mismatched-end-tag" 1 1]
         (take 4 (xml-err "</a>"))))
  (is (= [:xml/error "mismatched-end-tag" 1 8]
         (take 4 (xml-err "<a></a></a>"))))
  (is (= [:xml/error "mismatched-end-tag" 1 7]
         (take 4 (xml-err "<a><b></a></b>"))))
  ;; junk inside an end tag
  (is (= [:xml/error "unexpected-token" 1 8]
         (take 4 (xml-err "<a></a b>")))))

;; Strictness: EOF inside any construct is :unexpected-eof at the
;; EOF byte; unclosed elements never auto-balance.
(deftest xml-error-unexpected-eof
  (is (= [:xml/error "unexpected-eof" 1 4]
         (take 4 (xml-err "<a>"))))
  (is (= [:xml/error "unexpected-eof" 1 3]
         (take 4 (xml-err "<a"))))
  (is (= [:xml/error "unexpected-eof" 1 8]
         (take 4 (xml-err "<a b=\"x"))))
  (is (= [:xml/error "unexpected-eof" 1 9]
         (take 4 (xml-err "<a><!--x"))))
  (is (= [:xml/error "unexpected-eof" 1 18]
         (take 4 (xml-err "<a><![CDATA[x</a>"))))
  (is (= [:xml/error "unexpected-eof" 1 1]
         (take 4 (xml-err ""))))
  (is (= [:xml/error "unexpected-eof" 1 22]
         (take 4 (xml-err "<?xml version=\"1.0\"?>")))))

;; Strictness: markup-open characters that start no construct.
(deftest xml-error-unexpected-tokens
  (is (= [:xml/error "unexpected-token" 1 5]
         (take 4 (xml-err "<a> < b</a>"))))
  (is (= [:xml/error "unexpected-token" 1 1]
         (take 4 (xml-err "<3a/>"))))
  (is (= [:xml/error "unexpected-token" 1 1]
         (take 4 (xml-err "<!doctype a><a/>"))))
  ;; ]] must not appear literally in text
  (is (= [:xml/error "unexpected-token" 1 4]
         (take 4 (xml-err "<a>]]></a>"))))
  ;; NUL is not a legal XML character anywhere
  (is (= [:xml/error "unexpected-token" 1 5]
         (take 4 (xml-err (str "<a>x" (char 0) "y</a>"))))))

;; Comments: '--' inside comment content is not well-formed.
(deftest xml-error-comment-double-hyphen
  (is (= [:xml/error "unexpected-token" 1 9]
         (take 4 (xml-err "<a><!--a--b--></a>"))))
  (is (= [:xml/error "unexpected-token" 1 9]
         (take 4 (xml-err "<a><!--a---></a>")))))

;; Duplicate attributes reject (duplicates keeping the first is the
;; HTML rule; strict XML has no such tolerance).
(deftest xml-error-duplicate-attribute
  (is (= [:xml/error "duplicate-attribute" 1 10]
         (take 4 (xml-err "<a b=\"1\" b=\"2\"/>")))))

;; A-2 boundary pins: 256 open elements parse, 257 throw :max-depth
;; (the shared 256 cap; no synthesized wrappers in XML mode).
(defn- xml-deep-open [n] (str/join (repeat n "<a>")))

(deftest xml-error-max-depth-boundary
  (let [ok256 (xml-parse (str (xml-deep-open 256)
                              (str/join (repeat 256 "</a>")))
                         nil)]
    (is (map? ok256))
    (is (= 256 (loop [n ok256 d 1]
                 (if (seq (:content n))
                   (recur (nth (:content n) 0) (inc d))
                   d)))))
  (is (= [:xml/error "max-depth" 1 769]
         (take 4 (xml-err (xml-deep-open 257))))))

;; The prim returns the error descriptor vector; the facade owns
;; the ex-info throw (the toml.c split). :text is the source line.
(deftest xml-error-prim-descriptor-shape
  (let [r (xml-err "<a>\n<b></c>\n</a>")]
    (is (vector? r))
    (is (= :xml/error (nth r 0)))
    (is (= "mismatched-end-tag" (nth r 1)))
    (is (= 2 (nth r 2)))
    (is (= 4 (nth r 3)))
    (is (= "<b></c>" (nth r 4)))))

;;; ---- the clojure.xml mirror (p5t3) ----

(defn- xml-facade-err-data
  [thunk]
  (try (thunk) :no-throw (catch e (ex-data e))))

(defn- xml-facade-err-kind
  "Runs thunk and returns the thrown diagnostic's :mino/kind (ADR 37),
  or :no-throw if it returns."
  [thunk]
  (try (thunk) :no-throw (catch e (:mino/kind e))))

;; ADR 37: the facade throws a classified diagnostic; :mino/kind names
;; the error class at top level so classed catch dispatches on it.
(deftest xml-facade-diagnostic-is-classified
  ;; a bare catch binds the whole diagnostic; read :mino/kind off it
  (is (= :xml/parse
         (try (xml/parse "<a>&nbsp;</a>") (catch e (:mino/kind e)))))
  ;; a classed catch dispatches on :xml/parse
  (is (= :caught
         (try (xml/parse "<a/>\n<b/>") (catch :xml/parse _ :caught))))
  ;; opts errors carry :xml/opts and dispatch classed too
  (is (= :xml/opts (xml-facade-err-kind #(xml/parse 5))))
  (is (= :caught
         (try (xml/parse "<a/>" :nope) (catch :xml/opts _ :caught)))))

;; The facade converts the descriptor to a positioned diagnostic in the
;; yaml reader contract: :mino/kind classifies, ex-data carries
;; :code/:location/:text.
(deftest xml-facade-positioned-ex-info
  (let [d (xml-facade-err-data #(xml/parse "<a>&nbsp;</a>"))]
    (is (map? d))
    (is (= :xml/parse
           (try (xml/parse "<a>&nbsp;</a>") (catch e (:mino/kind e)))))
    (is (= :undefined-entity (:code d)))
    (is (= {:line 1 :col 4} (:location d)))
    (is (string? (:text d))))
  (let [d (xml-facade-err-data #(xml/parse "<a/>\n<b/>"))]
    (is (= :multiple-roots (:code d)))
    (is (= {:line 2 :col 1} (:location d))))
  (let [d (xml-facade-err-data
            #(xml/parse "<!DOCTYPE a [<!ENTITY e \"x\">]><a/>"))]
    (is (= :unsupported-doctype (:code d)))))

;; Divergence (AC-5): parse takes a STRING first (the JVM surface is
;; File/InputStream/URI); opts are keyword maps, reserved in v1.
(deftest xml-facade-string-first-surface
  (is (map? (xml/parse "<a/>")))
  (is (map? (xml/parse "<a/>" nil)))
  (is (map? (xml/parse "<a/>" {})))
  (is (= :xml/opts (xml-facade-err-kind #(xml/parse 5)))
      "input must be a string")
  (is (= :xml/opts (xml-facade-err-kind #(xml/parse "<a/>" :nope)))
      "opts must be a map"))

;; Divergence (AC-5): parse returns the root element map directly,
;; the JVM node shape without :type; attrs values are strings.
(deftest xml-facade-jvm-node-shape
  (let [t (xml/parse "<catalog kind=\"mix\" count=\"1452\"/>")]
    (is (map? t))
    (is (false? (contains? t :type)))
    (is (= :catalog (:tag t)))
    (is (= {:kind "mix" :count "1452"} (:attrs t)))
    (is (= [] (:content t)))
    (is (string? (:kind (:attrs t))))))

;;; ---- A-7: the junit parse-back proof (the in-repo customer) ----

(defn- xml-junit-probe-ns!
  "A scratch namespace with one passing and one failing test var
  (the test_tap_junit_test pattern; the probes never register with
  this file's suite)."
  []
  (when (find-ns 'xj.probe) (remove-ns 'xj.probe))
  (create-ns 'xj.probe)
  (let [pv (intern 'xj.probe 'probe-pass (fn [] (is (= 1 1))))
        fv (intern 'xj.probe 'probe-fail (fn [] (is (= 1 2))))]
    (alter-meta! pv assoc :test (var-get pv))
    (alter-meta! fv assoc :test (var-get fv))
    [pv fv]))

(defn- xml-junit-run
  "The captured clojure.test.junit emitter output for both probes
  inside one testsuite bracket."
  []
  (let [[pv fv] (xml-junit-probe-ns!)]
    (with-out-str
      (binding [*test-out*        *out*
                *report-counters* (atom *initial-report-counters*)]
        (junit/with-junit-output
          (do (do-report {:type :begin-test-ns :ns 'xj.probe})
              (test-var pv)
              (test-var fv)
              (do-report {:type :end-test-ns :ns 'xj.probe})))))))

;; A-7: clojure.xml/parse round-trips clojure.test.junit's emitter
;; output: the declaration parses, the testsuites tree comes back in
;; the JVM shape, counts are string attribute values, the passing
;; case is self-closed, and the failing case carries a nested
;; failure element whose escaped message and detail text decode.
(deftest xml-junit-emit-round-trips-through-parse
  (let [doc (xml-junit-run)
        tree (xml/parse doc)
        els (fn [content] (filterv map? content))
        suite (first (els (:content tree)))
        cases (els (:content suite))
        fail-case (second cases)
        failure (first (els (:content fail-case)))]
    (is (str/starts-with? doc "<?xml version=\"1.0\""))
    (is (= :testsuites (:tag tree)))
    ;; the emitter's newlines are character data inside the root and
    ;; stay verbatim string children (only whitespace OUTSIDE the
    ;; root drops)
    (is (= ["\n" "\n"] (filterv string? (:content tree))))
    (is (= :testsuite (:tag suite)))
    (is (= {:name     "xj.probe"
            :tests    "2"
            :failures "1"
            :errors   "0"}
           (:attrs suite)))
    (is (= 2 (count cases)))
    (is (= :testcase (:tag (first cases))))
    (is (= "probe-pass" (:name (:attrs (first cases)))))
    (is (= [] (:content (first cases))))
    (is (= "probe-fail" (:name (:attrs fail-case))))
    (is (= :failure (:tag failure)))
    (is (= "assertion failed" (:message (:attrs failure))))
    (is (str/includes? (first (filterv string? (:content failure)))
                       "expected:"))))

(run-tests-and-exit)
