#!/usr/bin/env python3
"""The zip CP437 name-table generator (ADR 29 D6, ADR 28 discipline).

Emits src/prim/zip_cp437.h: the 128-entry high-half CP437 table zip
entry names decode through when the language-encoding flag (bit 11)
is clear (the python zipfile behavior). The table is GENERATED from
the python cp437 codec, the same oracle the zip fixtures use; nothing
is vendored. Deterministic: the cp437 codec is frozen by Python's
stable-bytestring policy, so regeneration diffs empty on any python3:

    python3 tools/gen_zip_cp437.py

Usage: gen_zip_cp437.py  (writes src/prim/zip_cp437.h)
"""

import os

OUT = os.path.join("src", "prim", "zip_cp437.h")


def main():
    lines = []
    lines.append("/* zip_cp437.h -- the CP437 high-half name table (ADR 29 D6).")
    lines.append(" * Generated by tools/gen_zip_cp437.py from the python cp437")
    lines.append(" * codec; nothing vendored, nothing hand-edited (the ADR 28")
    lines.append(" * entity-table discipline). Regenerate:")
    lines.append(" *")
    lines.append(" *     python3 tools/gen_zip_cp437.py")
    lines.append(" *")
    lines.append(" * Entry i holds the UTF-8 encoding of CP437 byte 0x80+i, so zip")
    lines.append(" * names without the language-encoding flag (bit 11) decode")
    lines.append(" * exactly as python's zipfile decodes them (0x00-0x7F map to")
    lines.append(" * themselves and never consult this table).")
    lines.append(" */")
    lines.append("#ifndef MINO_ZIP_CP437_H")
    lines.append("#define MINO_ZIP_CP437_H")
    lines.append("")
    lines.append("static const char *const k_zip_cp437_high[128] = {")
    for i in range(128):
        byte = 0x80 + i
        char = bytes([byte]).decode("cp437")
        utf8 = char.encode("utf-8")
        esc = "".join("\\x%02x" % b for b in utf8)
        cp = "U+%04X" % ord(char)
        lines.append('    "%s", /* 0x%02x %s %s */' % (esc, byte, cp, char))
    lines.append("};")
    lines.append("")
    lines.append("#endif /* MINO_ZIP_CP437_H */")

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")

    print("gen_zip_cp437.py: wrote %s (128 entries)" % OUT)


if __name__ == "__main__":
    main()
