#!/usr/bin/env python3
"""The compression-zip campaign's python3 oracle generator (ADR 29).

Compress half (p2): emits the tests/fixtures/compress/ fixture set
the compress prims are pinned against -- the zlib.compress and gzip
member streams at levels 0/1/6/9 over a fixed deterministic corpus,
plus the pinned header vectors (the RFC 1952 10-byte header per
level bucket and the RFC 1950 CMF/FLG pair per level) in
manifest.edn. The zip half (p3) extends this script with the
zipfile-made oracle archives; it does not exist yet.

Golden split (R4): these oracle streams pin the DECODE side (mino
decompresses python's bytes) and the header vectors; compressed
BODIES are never compared between mino and any oracle (tdefl output
bytes are mino's own; only decode interop is claimed).

Deterministic by construction: fixed corpus, mtime pinned to 0, no
timestamps, no dict-order dependence, sorted output layout.
Regeneration must yield an empty diff:

    python3 tools/gen_zip_oracle.py

Oracle host: python3 zlib / gzip as of 3.14 (zlib level mapping and
gzip header fields verified against RFC 1950/1952 at this pin).

Usage: gen_zip_oracle.py  (writes under tests/fixtures/compress/)
"""

import gzip
import hashlib
import os
import zlib

HERE = os.path.join("tests", "fixtures", "compress")
LEVELS = (0, 1, 6, 9)


def compress_corpus():
    """Fixed, deterministic, compressible ~28 KB corpus."""
    parts = []
    for i in range(512):
        parts.append(
            "entry-%04d: The quick brown fox jumps over the lazy dog; "
            "pass %d of the compression oracle corpus\n" % (i, i % 7)
        )
    return ("".join(parts)).encode("utf-8")


def sha256_hex(data):
    return hashlib.sha256(data).hexdigest()


def edn_vector(bytes_):
    return "[" + " ".join(str(b) for b in bytes_) + "]"


def main():
    corpus = compress_corpus()
    os.makedirs(HERE, exist_ok=True)

    with open(os.path.join(HERE, "corpus.txt"), "wb") as f:
        f.write(corpus)

    levels_edn = []
    for level in LEVELS:
        z = zlib.compress(corpus, level)
        g = gzip.compress(corpus, compresslevel=level, mtime=0)
        with open(os.path.join(HERE, "zlib_l%d.bin" % level), "wb") as f:
            f.write(z)
        with open(os.path.join(HERE, "gzip_l%d.gz" % level), "wb") as f:
            f.write(g)
        levels_edn.append(
            " {:level %d\n"
            "  :zlib-size %d\n"
            "  :zlib-sha256 \"%s\"\n"
            "  :gzip-size %d\n"
            "  :gzip-sha256 \"%s\"\n"
            "  :gzip-header %s\n"
            "  :zlib-cmf-flg %s}\n"
            % (
                level,
                len(z),
                sha256_hex(z),
                len(g),
                sha256_hex(g),
                edn_vector(g[:10]),
                edn_vector(z[:2]),
            )
        )

    with open(os.path.join(HERE, "manifest.edn"), "w") as f:
        f.write(
            ";; GENERATED by tools/gen_zip_oracle.py -- do not edit.\n"
            ";;\n"
            ";; Regenerate: python3 tools/gen_zip_oracle.py\n"
            ";; (empty diff on regeneration; python3 3.14 zlib/gzip is\n"
            ";; the oracle). :gzip-header is python's RFC 1952 10-byte\n"
            ";; header (mtime 0, no name, OS 255, XFL per level);\n"
            ";; :zlib-cmf-flg is python's RFC 1950 CMF/FLG pair. The\n"
            ";; header vectors pin mino's writers byte for byte; the\n"
            ";; streams themselves pin mino's zlib-decompress (decode\n"
            ";; interop only, R4: compressed bodies are never compared).\n"
            "{:corpus-size %d\n"
            " :corpus-sha256 \"%s\"\n"
            " :levels\n"
            " [%s]}\n"
            % (len(corpus), sha256_hex(corpus), "".join(levels_edn))
        )

    with open(os.path.join(HERE, "README.md"), "w") as f:
        f.write(
            "# compress test fixtures\n"
            "\n"
            "Generated by `tools/gen_zip_oracle.py` (the python3 zlib /\n"
            "gzip oracle; provenance in manifest.edn):\n"
            "\n"
            "```\n"
            "python3 tools/gen_zip_oracle.py\n"
            "```\n"
            "\n"
            "- `corpus.txt` -- the deterministic compressible corpus.\n"
            "- `zlib_l{0,1,6,9}.bin` -- `zlib.compress(corpus, level)`\n"
            "  streams; mino's zlib-decompress must decode each one.\n"
            "- `gzip_l{0,1,6,9}.gz` -- `gzip.compress(corpus,\n"
            "  compresslevel=level, mtime=0)` members.\n"
            "- `manifest.edn` -- sizes, SHA-256s, and the pinned header\n"
            "  vectors. Compressed bodies are never compared between\n"
            "  mino and python (the R4 golden split): the streams pin\n"
            "  the decode side, the header vectors pin the writers.\n"
            "\n"
            "A regenerated `random*`-style fixture does not exist here;\n"
            "the corpus is fully deterministic, so regeneration diffs\n"
            "empty on the same python3/zlib.\n"
        )

    print("gen_zip_oracle.py: wrote %s (%d byte corpus)" % (HERE, len(corpus)))


if __name__ == "__main__":
    main()
