#!/usr/bin/env python3
"""Generate src/prim/html_entities.c and src/prim/html_entities.h
from the python3 stdlib entity oracle (html.entities.html5), the
corpus the html-xml campaign pins (ADR 28; design D11).

Every entry of html.entities.html5 is emitted verbatim: names keep
their html5 spelling (semicolon forms carry the ';', the legacy
semicolonless forms do not), values are the entity's expansion as
UTF-8. Names are sorted canonically (byte order, not dict order,
R-6) so the C side can longest-match with a plain binary search.

Non-ASCII and non-printable value bytes are emitted as three-digit
octal escapes (never \\xNN: C hex escapes are greedy and would eat
a following hex digit). No timestamps, no version stamps: the table
content is the oracle dict itself, stable across modern python3.

Regeneration must yield an empty diff:
    python3 tools/gen_html_entities.py
    git diff --exit-code src/prim/html_entities.c src/prim/html_entities.h
"""

import html.entities
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_C = os.path.join(ROOT, "src/prim/html_entities.c")
OUT_H = os.path.join(ROOT, "src/prim/html_entities.h")


def c_string(s: str) -> str:
    """One C string literal for a python str, octal-escaped where
    not safely printable ASCII."""
    out = []
    for byte in s.encode("utf-8"):
        if 0x20 <= byte < 0x7F and byte not in (0x22, 0x5C):  # not " or backslash
            out.append(chr(byte))
        else:
            out.append("\\%03o" % byte)
    return '"%s"' % "".join(out)


def main() -> None:
    table = sorted(html.entities.html5.items(), key=lambda kv: kv[0].encode("utf-8"))

    rows = []
    for name, value in table:
        if isinstance(value, tuple):
            value = "".join(value)
        rows.append("    {%s, %s}," % (c_string(name), c_string(value)))

    count = len(rows)
    header_c = """\
/* HTML named-entity table. Generated by
 * tools/gen_html_entities.py from the python3 stdlib oracle
 * (html.entities.html5); do not edit by hand.
 *
 * %d entries (name keys exactly as html5 spells them, ';'-suffixed
 * semicolon forms and legacy bare forms alike), canonically sorted
 * by name bytes; the tokenizer looks them up by longest match.
 * Values are UTF-8, octal-escaped where not printable ASCII.
 */
#include "html_entities.h"

const mino_html_entity_t k_html_entities[%d] = {
%s
};

const unsigned k_html_entities_count = %d;
""" % (count, count, "\n".join(rows), count)

    header_h = """\
/* Declarations for the generated HTML entity table (ADR 28).
 * Generated alongside src/prim/html_entities.c by
 * tools/gen_html_entities.py; do not edit by hand.
 */
#ifndef MINO_HTML_ENTITIES_H
#define MINO_HTML_ENTITIES_H

typedef struct mino_html_entity_s {
    const char *name;  /* html5 spelling; ';' included when required */
    const char *value; /* UTF-8 expansion, NUL-terminated */
} mino_html_entity_t;

extern const mino_html_entity_t k_html_entities[%d];
extern const unsigned k_html_entities_count;

#endif /* MINO_HTML_ENTITIES_H */
""" % count

    with open(OUT_C, "w") as f:
        f.write(header_c)
    with open(OUT_H, "w") as f:
        f.write(header_h)
    print("wrote %s and %s: %d entities" % (OUT_C, OUT_H, count))


if __name__ == "__main__":
    main()
