static const char *lib_mino_html_src =
    "(ns mino.html\n"
    "  \"Tolerant HTML reader over hickory-shaped node maps (ADR 28).\n"
    "\n"
    "  (require '[mino.html :as html])\n"
    "  (html/parse \\\"<p>hello\\\")                ; => the document node map\n"
    "  (html/parse-fragment \\\"<p>a<p>b\\\")       ; => [node node]\n"
    "\n"
    "  Nodes are plain maps: elements {:type :element :tag keyword\n"
    "  :attrs {keyword string} :content [node|string]} with lowercase tag\n"
    "  and attribute names, {:type :comment :content [text]},\n"
    "  {:type :document-type :content [text]} for the first DOCTYPE, and\n"
    "  text as bare strings inside :content. parse returns the document\n"
    "  map {:type :document :content [...]} directly with synthesized\n"
    "  html/head/body wrappers when absent (explicit tags win);\n"
    "  parse-fragment returns a vector of top-level nodes with no\n"
    "  synthesis and no wrapper.\n"
    "\n"
    "  The reader is the native single-pass html-parse prim (ADR 28, the\n"
    "  json/csv/toml/yaml reader lineage) implementing the campaign's\n"
    "  pinned tolerance tier: unclosed tags auto-balance at EOF, stray end\n"
    "  tags drop, misnested end tags pop-until, the WHATWG void list, the\n"
    "  trailing solidus honored on every start tag, script/style RAWTEXT\n"
    "  with title/textarea RCDATA, entity decoding through the\n"
    "  python-oracle table (semicolonless legacy names resolve in text,\n"
    "  semicolon-terminated names only inside attribute values), bogus\n"
    "  comments, name lowercasing, PLAINTEXT rest-of-input, and NUL to\n"
    "  U+FFFD in text. This namespace owns argument validation and the\n"
    "  error contract: errors throw ex-info with :kind :html/parse, a\n"
    "  :code keyword, :location {:line :col} (1-based, bytes), and the\n"
    "  offending :text (source line). v1 code: :max-depth (the 256\n"
    "  open-element cap; everything else recovers).\n"
    "\n"
    "  Divergences from hickory, pinned by tests: parse returns the node\n"
    "  map directly (no parser object), and malformed input a browser\n"
    "  would recover from yields either the recovered tree or a positioned\n"
    "  ex-info where hickory never throws. opts are keyword maps,\n"
    "  reserved and ignored in v1.\"\n"
    "  (:require [clojure.string :as str]))\n"
    "\n"
    "(defn- throw-opts\n"
    "  [msg arg]\n"
    "  (throw (ex-info (str \"mino.html: \" msg)\n"
    "                  {:kind :html/opts :arg arg})))\n"
    "\n"
    "(defn- run-prim\n"
    "  [who s opts fragment]\n"
    "  (when-not (string? s)\n"
    "    (throw-opts (str who \" requires a string\") s))\n"
    "  (when-not (or (nil? opts) (map? opts))\n"
    "    (throw-opts (str who \" opts must be a map\") opts))\n"
    "  (let [r (html-parse s (if fragment {:fragment true} nil))]\n"
    "    (if (and (vector? r)\n"
    "             (seq r)\n"
    "             (= :html/error (nth r 0)))\n"
    "      (throw (ex-info (str \"mino.html: \" (nth r 1))\n"
    "                      {:kind :html/parse\n"
    "                       :code (keyword (nth r 1))\n"
    "                       :location {:line (nth r 2)\n"
    "                                  :col (nth r 3)}\n"
    "                       :text (nth r 4)}))\n"
    "      r)))\n"
    "\n"
    "(defn parse\n"
    "  \"Parses s as an HTML document into the hickory-shaped document node\n"
    "  map {:type :document :content [...]}, synthesizing html/head/body\n"
    "  wrappers when absent (explicit tags win; head elements that precede\n"
    "  body content route into head; leading whitespace drops).\n"
    "\n"
    "  (html/parse \\\"<p>hello\\\")\n"
    "  => {:type :document :content [{:type :element :tag :html ...}]}\n"
    "\n"
    "  opts is a keyword map, reserved and accepted but ignored in v1.\n"
    "  Throws ex-info :kind :html/parse with :code, :location {:line\n"
    "  :col}, and :text on the only non-recovering edge, the 256-deep\n"
    "  open-element cap (:code :max-depth).\"\n"
    "  ([s] (parse s nil))\n"
    "  ([s opts]\n"
    "   (run-prim \"parse\" s opts false)))\n"
    "\n"
    "(defn parse-fragment\n"
    "  \"Parses s as a fragment: a vector of top-level nodes with no\n"
    "  document wrapper, no implied html/head/body, and whitespace text\n"
    "  kept verbatim. Tolerance rules 1-16 (implied closes, stray-end\n"
    "  drop, pop-until, void, solidus, raw text, entities) still apply.\n"
    "\n"
    "  (html/parse-fragment \\\"<li>a<li>b\\\")\n"
    "  => [{:type :element :tag :li :content [\\\"a\\\"]} {:type :element :tag :li ...}]\n"
    "\n"
    "  Options and the error contract are as in parse.\"\n"
    "  ([s] (parse-fragment s nil))\n"
    "  ([s opts]\n"
    "   (run-prim \"parse-fragment\" s opts true)))\n"
    ;
