static const char *lib_mino_html_src =
    "(ns mino.html\n"
    "  \"Tolerant HTML reader over hickory-shaped node maps (ADR 28).\n"
    "\n"
    "  (require '[mino.html :as html])\n"
    "  (html/parse \\\"<p>hello\\\")                ; => the document node map\n"
    "  (html/parse-fragment \\\"<p>a<p>b\\\")       ; => [node node]\n"
    "  (html/to-html (html/parse \\\"<p>x\\\"))     ; => \\\"<html>...</html>\\\"\n"
    "\n"
    "  Nodes are plain maps: elements {:type :element :tag keyword\n"
    "  :attrs {keyword string} :content [node|string]} with lowercase tag\n"
    "  and attribute names, {:type :comment :content [text]},\n"
    "  {:type :document-type :content [text]} for the first DOCTYPE, and\n"
    "  text as bare strings inside :content. parse returns the document\n"
    "  map {:type :document :content [...]} directly with synthesized\n"
    "  html/head/body wrappers when absent (explicit tags win);\n"
    "  parse-fragment returns a vector of top-level nodes with no\n"
    "  synthesis and no wrapper.\n"
    "\n"
    "  The reader is the native single-pass html-parse prim (ADR 28, the\n"
    "  json/csv/toml/yaml reader lineage) implementing the campaign's\n"
    "  pinned tolerance tier: unclosed tags auto-balance at EOF, stray end\n"
    "  tags drop, misnested end tags pop-until, the WHATWG void list, the\n"
    "  trailing solidus honored on every start tag, script/style RAWTEXT\n"
    "  with title/textarea RCDATA, entity decoding through the\n"
    "  python-oracle table (semicolonless legacy names resolve in text,\n"
    "  semicolon-terminated names only inside attribute values), bogus\n"
    "  comments, name lowercasing, PLAINTEXT rest-of-input, and NUL to\n"
    "  U+FFFD in text. This namespace owns argument validation and the\n"
    "  error contract: errors throw ex-info with :kind :html/parse, a\n"
    "  :code keyword, :location {:line :col} (1-based, bytes), and the\n"
    "  offending :text (source line). v1 code: :max-depth (the 256\n"
    "  open-element cap; everything else recovers).\n"
    "\n"
    "  Divergences from hickory, pinned by tests: parse returns the node\n"
    "  map directly (no parser object), and malformed input a browser\n"
    "  would recover from yields either the recovered tree or a positioned\n"
    "  ex-info where hickory never throws. opts are keyword maps,\n"
    "  reserved and ignored in v1.\"\n"
    "  (:require [clojure.string :as str]))\n"
    "\n"
    "(defn- throw-opts\n"
    "  [msg arg]\n"
    "  (throw (ex-info (str \"mino.html: \" msg)\n"
    "                  {:kind :html/opts :arg arg})))\n"
    "\n"
    "(defn- run-prim\n"
    "  [who s opts fragment]\n"
    "  (when-not (string? s)\n"
    "    (throw-opts (str who \" requires a string\") s))\n"
    "  (when-not (or (nil? opts) (map? opts))\n"
    "    (throw-opts (str who \" opts must be a map\") opts))\n"
    "  (let [r (html-parse s (if fragment {:fragment true} nil))]\n"
    "    (if (and (vector? r)\n"
    "             (seq r)\n"
    "             (= :html/error (nth r 0)))\n"
    "      (throw (ex-info (str \"mino.html: \" (nth r 1))\n"
    "                      {:kind :html/parse\n"
    "                       :code (keyword (nth r 1))\n"
    "                       :location {:line (nth r 2)\n"
    "                                  :col (nth r 3)}\n"
    "                       :text (nth r 4)}))\n"
    "      r)))\n"
    "\n"
    "(defn parse\n"
    "  \"Parses s as an HTML document into the hickory-shaped document node\n"
    "  map {:type :document :content [...]}, synthesizing html/head/body\n"
    "  wrappers when absent (explicit tags win; head elements that precede\n"
    "  body content route into head; leading whitespace drops).\n"
    "\n"
    "  (html/parse \\\"<p>hello\\\")\n"
    "  => {:type :document :content [{:type :element :tag :html ...}]}\n"
    "\n"
    "  opts is a keyword map, reserved and accepted but ignored in v1.\n"
    "  Throws ex-info :kind :html/parse with :code, :location {:line\n"
    "  :col}, and :text on the only non-recovering edge, the 256-deep\n"
    "  open-element cap (:code :max-depth).\"\n"
    "  ([s] (parse s nil))\n"
    "  ([s opts]\n"
    "   (run-prim \"parse\" s opts false)))\n"
    "\n"
    "(defn parse-fragment\n"
    "  \"Parses s as a fragment: a vector of top-level nodes with no\n"
    "  document wrapper, no implied html/head/body, and whitespace text\n"
    "  kept verbatim. Tolerance rules 1-16 (implied closes, stray-end\n"
    "  drop, pop-until, void, solidus, raw text, entities) still apply.\n"
    "\n"
    "  (html/parse-fragment \\\"<li>a<li>b\\\")\n"
    "  => [{:type :element :tag :li :content [\\\"a\\\"]} {:type :element :tag :li ...}]\n"
    "\n"
    "  Options and the error contract are as in parse.\"\n"
    "  ([s] (parse-fragment s nil))\n"
    "  ([s opts]\n"
    "   (run-prim \"parse-fragment\" s opts true)))\n"
    "\n"
    ";;; ---- serializer (design D10; the writer stays Clojure, ADR 23/24) ----\n"
    "\n"
    ";; The serializer is one explicit worklist loop, no per-node closures\n"
    ";; and no case dispatch (the interpreter's per-call constants make\n"
    ";; recursive closure walkers 30x slower at megabyte scale; the html\n"
    ";; scaling gate pins this).\n"
    "\n"
    "(def ^:private html-text-re #\"[&<>]\")\n"
    "(def ^:private html-text-esc {\"&\" \"&amp;\" \"<\" \"&lt;\" \">\" \"&gt;\"})\n"
    "(def ^:private html-attr-re #\"[&\\\"]\")\n"
    "(def ^:private html-attr-esc {\"&\" \"&amp;\" \"\\\"\" \"&quot;\"})\n"
    "\n"
    "(def ^:private html-tag-class\n"
    "  \"Element classes with special emission: :void elements emit no end\n"
    "  tag (WHATWG tier rule 4 list); :script/:style are RAWTEXT and\n"
    "  :plaintext rest-of-input (their string children emit verbatim,\n"
    "  D6/D10); everything else (nil) opens and closes normally.\"\n"
    "  {:area :void :base :void :br :void :col :void :embed :void :hr :void\n"
    "   :img :void :input :void :link :void :meta :void :param :void\n"
    "   :source :void :track :void :wbr :void\n"
    "   :script :raw :style :raw :plaintext :plain})\n"
    "\n"
    "(defn- html-escape-text\n"
    "  \"Text content: amp lt gt, the D10 minimal spelling for text. One\n"
    "  regex pass, skipped when clean (re-find is the cheap scan);\n"
    "  escaping amp first is inherent (no double escapes).\"\n"
    "  [s]\n"
    "  (if (re-find html-text-re s)\n"
    "    (str/replace s html-text-re html-text-esc)\n"
    "    s))\n"
    "\n"
    "(defn- html-escape-attr\n"
    "  \"Attribute values: amp quot. Double quotes delimit the value, so\n"
    "  quot is structural; lt and gt stay raw (a quoted value reparses\n"
    "  them unchanged).\"\n"
    "  [s]\n"
    "  (if (re-find html-attr-re s)\n"
    "    (str/replace s html-attr-re html-attr-esc)\n"
    "    s))\n"
    "\n"
    "(defn- html-attrs-str\n"
    "  \"Attributes in map order (written order survives parse), each\n"
    "  value double-quoted; a nil or empty map emits nothing.\"\n"
    "  [attrs]\n"
    "  (if (seq attrs)\n"
    "    (loop [es (seq attrs) acc \"\"]\n"
    "      (if es\n"
    "        (let [e (first es)]\n"
    "          (recur (next es)\n"
    "                 (str acc \" \" (name (key e)) \"=\\\"\"\n"
    "                      (html-escape-attr (str (val e))) \"\\\"\")))\n"
    "        acc))\n"
    "    \"\"))\n"
    "\n"
    "(defn- html-push-all\n"
    "  \"Conjs the entries onto the worklist in reverse, so they pop in\n"
    "  written order.\"\n"
    "  [st entries]\n"
    "  (if (vector? entries)\n"
    "    (into st (rseq entries))\n"
    "    (into st (reverse entries))))\n"
    "\n"
    "(defn- html-push-raw\n"
    "  \"Like html-push-all but wraps string children as verbatim markers\n"
    "  (RAWTEXT and PLAINTEXT interiors; anything else serializes\n"
    "  normally). Index walk: seq materialization over large vectors is\n"
    "  O(n) in this runtime.\"\n"
    "  [st children]\n"
    "  (if (vector? children)\n"
    "    (let [n (count children)]\n"
    "      (loop [i (dec n) st st]\n"
    "        (if (>= i 0)\n"
    "          (let [c (nth children i)]\n"
    "            (recur (dec i) (conj st (if (string? c) [c] c))))\n"
    "          st)))\n"
    "    (loop [cs (reverse children) st st]\n"
    "      (if cs\n"
    "        (let [c (first cs)]\n"
    "          (recur (next cs) (conj st (if (string? c) [c] c))))\n"
    "        st))))\n"
    "\n"
    "(defn- html-push-element\n"
    "  \"Rewrites the worklist for the element's content: normal elements\n"
    "  get their close tag beneath the children, void elements none,\n"
    "  RAWTEXT a close tag beneath verbatim children, PLAINTEXT no close\n"
    "  tag at all (an end tag would join the verbatim run on reparse).\n"
    "  Returns the new worklist.\"\n"
    "  [x st]\n"
    "  (let [tag (name (:tag x))\n"
    "        cls (get html-tag-class (:tag x))\n"
    "        content (or (:content x) [])]\n"
    "    (if (nil? cls)\n"
    "      (html-push-all (conj st [(str \"</\" tag \">\")]) content)\n"
    "      (if (identical? cls :void)\n"
    "        (html-push-all st content)\n"
    "        (if (identical? cls :raw)\n"
    "          (html-push-raw (conj st [(str \"</\" tag \">\")]) content)\n"
    "          (html-push-raw st content))))))\n"
    "\n"
    "(defn- html-serialize\n"
    "  \"The worklist walk: entries are node maps (emitted by type), bare\n"
    "  strings (escaped text), or one-element vectors (verbatim string\n"
    "  fragments: close tags, RAWTEXT interiors).\"\n"
    "  [node]\n"
    "  (loop [st (if (sequential? node)\n"
    "              (html-push-all [] node)\n"
    "              [node])\n"
    "         acc (transient [])]\n"
    "    (if (pos? (count st))\n"
    "      (let [x (peek st)\n"
    "            st (pop st)]\n"
    "        (cond\n"
    "          (string? x)\n"
    "          (recur st (conj! acc (html-escape-text x)))\n"
    "\n"
    "          (vector? x)\n"
    "          (recur st (conj! acc (nth x 0)))\n"
    "\n"
    "          (map? x)\n"
    "          (let [typ (:type x)]\n"
    "            (cond\n"
    "              (= :element typ)\n"
    "              (recur (html-push-element x st)\n"
    "                     (conj! acc (str \"<\" (name (:tag x))\n"
    "                                     (html-attrs-str (:attrs x)) \">\")))\n"
    "\n"
    "              (= :document typ)\n"
    "              (recur (html-push-all st (or (:content x) [])) acc)\n"
    "\n"
    "              (= :comment typ)\n"
    "              (recur st (conj! acc (str \"<!--\"\n"
    "                                        (or (first (:content x)) \"\")\n"
    "                                        \"-->\")))\n"
    "\n"
    "              (= :document-type typ)\n"
    "              (recur st (conj! acc (str \"<!DOCTYPE \"\n"
    "                                        (or (first (:content x)) \"\")\n"
    "                                        \">\")))\n"
    "\n"
    "              (nil? typ)\n"
    "              ;; the shared JVM clojure.xml element shape: XML trees\n"
    "              ;; round-trip through to-html on :tag/:attrs/:content\n"
    "              (if (contains? x :tag)\n"
    "                (recur (html-push-element x st)\n"
    "                       (conj! acc (str \"<\" (name (:tag x))\n"
    "                                       (html-attrs-str (:attrs x)) \">\")))\n"
    "                (throw-opts \"to-html requires a node with :type or :tag\" x))\n"
    "\n"
    "              :else (throw-opts \"to-html got an unknown node :type\" typ)))\n"
    "\n"
    "          (sequential? x)\n"
    "          (recur (html-push-all st x) acc)\n"
    "\n"
    "          :else (throw-opts \"to-html requires a node\" x)))\n"
    "      (str/join (persistent! acc)))))\n"
    "\n"
    "(defn to-html\n"
    "  \"Serializes node into HTML text. node may be a hickory node map\n"
    "  (:document, :element, :comment, :document-type), a bare text\n"
    "  string, a collection of nodes (fragment serialization), or a JVM\n"
    "  clojure.xml element map ({:tag :attrs :content}; the shared shape,\n"
    "  so XML trees round-trip through this fn).\n"
    "\n"
    "  (html/to-html (html/parse \\\"<p>hello\\\"))\n"
    "  => \\\"<html><head></head><body><p>hello</p></body></html>\\\"\n"
    "\n"
    "  Normalization (design D10, pinned by tests/html_serialize_test):\n"
    "  names emit as written (parse lowercased them in HTML mode);\n"
    "  attribute order preserved as written; attribute values always\n"
    "  double-quoted with amp and quot escaped (lt and gt stay raw);\n"
    "  valueless attributes emit as name=\\\"\\\"; adjacent text runs merge\n"
    "  and empty text runs vanish (unrepresentable in HTML); entities\n"
    "  re-emit minimally (amp lt gt escaped in text and RCDATA content;\n"
    "  nothing escaped in RAWTEXT content); void elements emit without\n"
    "  end tags; every non-void element is explicitly closed, so implied\n"
    "  closes and the synthesized html/head/body wrappers materialize;\n"
    "  comments and the DOCTYPE text emit verbatim; script, style, and\n"
    "  PLAINTEXT content emits verbatim (RCDATA title/textarea content\n"
    "  re-encodes like text, D6).\n"
    "\n"
    "  Contract: (parse (to-html (parse s))) equals (parse s) modulo the\n"
    "  adjacent-run merge for every input the tolerance tier accepts, and\n"
    "  output is byte-exact over canonical-form fixtures (lowercase\n"
    "  names, double-quoted values, explicit closes). opts is a keyword\n"
    "  map, reserved and accepted but ignored in v1; invalid nodes and\n"
    "  opts throw ex-info :kind :html/opts.\"\n"
    "  ([node] (to-html node nil))\n"
    "  ([node opts]\n"
    "   (when-not (or (nil? opts) (map? opts))\n"
    "     (throw-opts \"to-html opts must be a map\" opts))\n"
    "   (html-serialize node)))\n"
    ;
