name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Compiler version
        run: cc --version

      - name: Bootstrap
        run: make

      - name: Test
        run: ./mino task test
